/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlBaja extends javax.swing.JPanel {

    Empresa empresa;
    DefaultComboBoxModel modeloUsuarios;
    Usuario usuario;

    /**
     *
     * @param empresa
     * @param usuario
     */
    public PnlBaja(Empresa empresa, Usuario usuario) {
        initComponents();
        this.empresa = empresa;
        this.usuario = usuario;
        modeloUsuarios = new DefaultComboBoxModel();
        cmbUsuarios.setModel(modeloUsuarios);
        cargarUsuarios();
        btnEliminar.setEnabled(false);
    }

    /**
     * carga como con los usuarios
     */
    private void cargarUsuarios() {
        modeloUsuarios.addElement("Seleccione un usuario");
        modeloUsuarios.addAll(empresa.getUsuarios());
    }

    /**
     * Restaura la pantalla a su estado por defecto
     */
    private void limpiar() {
        lblNombre.setText("");
        lblEmail.setText("");
        cmbUsuarios.setSelectedIndex(0);//vuelve paradas colocar la primera opcion
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbUsuarios.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });
        add(cmbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 204));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 153, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 204));
        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 153, 153));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 200, 30));

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 200, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Dirección:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Baja Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        int pos = cmbUsuarios.getSelectedIndex();//dame la posición seleccionada
        if (pos != 0) {
            Usuario u = (Usuario) modeloUsuarios.getElementAt(pos);//dame el seleccionado
            lblNombre.setText(u.getNombre());
            lblEmail.setText(u.getEmail());
            if (u.getNombre().equals(usuario.getNombre())) {
                btnEliminar.setEnabled(false);
            } else {
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Usuario u = (Usuario) cmbUsuarios.getSelectedItem();
        if (u == null) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún usuario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            empresa.getUsuarios().remove(u);
            cmbUsuarios.removeItem(u);
            JOptionPane.showMessageDialog(this, "Usuario Eliminado", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
