/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlCambioContraPropia extends javax.swing.JPanel {

    Empresa empresa;
    Usuario usuario;

    /**
     *
     * @param empresa
     * @param usuario
     */
    public PnlCambioContraPropia(Empresa empresa, Usuario usuario) {
        initComponents();
        this.empresa = empresa;
        this.usuario = usuario;
    }

    /**
     * Restaura la pantalla a su estado por defecto
     */
    private void limpiar() {
        pwdActual.setText("");
        pwdNueva.setText("");
        pwdNueva2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pwdNueva2 = new javax.swing.JPasswordField();
        pwdNueva = new javax.swing.JPasswordField();
        pwdActual = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setBackground(new java.awt.Color(255, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 153, 153));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 204));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 153, 153));
        btnCancelar.setText("Cancelar");
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Contraseña actual");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 190, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Nueva contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Confirmar contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        pwdNueva2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add(pwdNueva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 30));

        pwdNueva.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add(pwdNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 30));

        pwdActual.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add(pwdActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 30));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Cambio contraseña");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String actual = new String(pwdActual.getPassword());
        if (!usuario.getContra().equals(actual)) {
            pwdActual.setText("");
            pwdActual.requestFocus();
            JOptionPane.showMessageDialog(this, "Contraseña actual incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String nueva = new String(pwdNueva.getPassword());
            String nueva2 = new String(pwdNueva2.getPassword());
            if (!nueva.equals(nueva2)) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
                pwdNueva.setText("");
                pwdNueva2.setText("");
            } else {
                usuario.setContra(nueva);
                JOptionPane.showMessageDialog(this, "Se ha cambiado la contraseña correctamente.", "Cambio realizado", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwdActual;
    private javax.swing.JPasswordField pwdNueva;
    private javax.swing.JPasswordField pwdNueva2;
    // End of variables declaration//GEN-END:variables
}
