/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlCambioContraUsu extends javax.swing.JPanel {

    Empresa empresa;
    DefaultComboBoxModel modeloUsuarios;

    /**
     *
     * @param empresa
     */
    public PnlCambioContraUsu(Empresa empresa) {
        initComponents();
        this.empresa = empresa;

        modeloUsuarios = new DefaultComboBoxModel();
        cmbUsuarios.setModel(modeloUsuarios);
        cargarUsuarios();
        limpiar();
    }

    /**
     * Carga al combo los usuarios existentes
     */
    private void cargarUsuarios() {
        modeloUsuarios.addElement("Seleccione un usuario");
        modeloUsuarios.addAll(empresa.getUsuarios());
    }

    /**
     * Restaura la pantalla a su estado por defecto
     */
    private void limpiar() {
        cmbUsuarios.setSelectedIndex(0);//vuelve paradas colocar la primera opcion
        pwdNueva.setText("");
        pwdNueva2.setText("");
        lblNueva.setVisible(false);
        lblNueva2.setVisible(false);
        btnAceptar.setEnabled(false);
        pwdNueva.setVisible(false);
        pwdNueva2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pwdNueva2 = new javax.swing.JPasswordField();
        pwdNueva = new javax.swing.JPasswordField();
        cmbUsuarios = new javax.swing.JComboBox<>();
        lblNueva2 = new javax.swing.JLabel();
        lblNueva = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setBackground(new java.awt.Color(255, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 153, 153));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 204));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 153, 153));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        pwdNueva2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pwdNueva2.setForeground(new java.awt.Color(0, 204, 204));
        add(pwdNueva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 40));

        pwdNueva.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pwdNueva.setForeground(new java.awt.Color(0, 204, 204));
        add(pwdNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, 40));

        cmbUsuarios.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cmbUsuarios.setForeground(new java.awt.Color(0, 204, 204));
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });
        add(cmbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 420, 40));

        lblNueva2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblNueva2.setForeground(new java.awt.Color(0, 204, 204));
        lblNueva2.setText("Confirmar contraseña");
        add(lblNueva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        lblNueva.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblNueva.setForeground(new java.awt.Color(0, 204, 204));
        lblNueva.setText("Nueva contraseña");
        add(lblNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Enviar nueva contraseña");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Usuario usuario = (Usuario) cmbUsuarios.getSelectedItem();//devuelve el objeto seleccionado
        String nueva = new String(pwdNueva.getPassword());
        String nueva2 = new String(pwdNueva2.getPassword());
        if (!nueva.equals(nueva2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            pwdNueva.setText("");
            pwdNueva2.setText("");
        } else {
            usuario.setContra(nueva);
            JOptionPane.showMessageDialog(this, "Se ha cambiado la contraseña correctamente.", "Cambio realizado", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        int pos = cmbUsuarios.getSelectedIndex();//dame el seleccionado
        if (pos != 0) {
            btnAceptar.setEnabled(true);
            lblNueva.setVisible(true);
            lblNueva2.setVisible(true);
            pwdNueva.setVisible(true);
            pwdNueva2.setVisible(true);
        }
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNueva;
    private javax.swing.JLabel lblNueva2;
    private javax.swing.JPasswordField pwdNueva;
    private javax.swing.JPasswordField pwdNueva2;
    // End of variables declaration//GEN-END:variables
}
