/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import javax.swing.DefaultComboBoxModel;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlConsultaUsu extends javax.swing.JPanel {

    Empresa empresa;
    DefaultComboBoxModel modeloUsuarios;

    /**
     *
     * @param empresa
     */
    public PnlConsultaUsu(Empresa empresa) {
        initComponents();
        this.empresa = empresa;
        modeloUsuarios = new DefaultComboBoxModel();
        cmbUsuarios.setModel(modeloUsuarios);
        cargarUsuarios();
        btnAceptar.setEnabled(false);
    }

    /**
     * Restaura la pantalla a su estado por defecto
     */
    private void limpiar() {
        lblNombre.setText("");
        lblEmail.setText("");
        chckAdmin.setSelected(false);
        chckEstandar.setSelected(false);
    }

    /**
     * carga al combo los usuarios existentes
     */
    private void cargarUsuarios() {
        modeloUsuarios.addElement("Seleccione un usuario");
        modeloUsuarios.addAll(empresa.getUsuarios());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        chckAdmin = new javax.swing.JCheckBox();
        chckEstandar = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbUsuarios.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cmbUsuarios.setForeground(new java.awt.Color(0, 153, 153));
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });
        add(cmbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 280, 40));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Consulta usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 50));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Dirección:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 204, 204));
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 40));

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 204, 204));
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, 40));

        chckAdmin.setBackground(new java.awt.Color(255, 204, 204));
        chckAdmin.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chckAdmin.setText("Administrador");
        add(chckAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        chckEstandar.setBackground(new java.awt.Color(255, 204, 204));
        chckEstandar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chckEstandar.setText("Usuario");
        add(chckEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(255, 255, 204));
        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 153, 153));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        int pos = cmbUsuarios.getSelectedIndex();//dame el seleccionado
        if (pos != 0) {
            Usuario u = (Usuario) modeloUsuarios.getElementAt(pos);//dame el seleccionado
            lblNombre.setText(u.getNombre());
            lblEmail.setText(u.getEmail());
            if (u.getPerfil() == 1) {
                chckAdmin.setSelected(true);
                chckEstandar.setSelected(false);
            } else {
                chckEstandar.setSelected(true);
                chckAdmin.setSelected(false);
            }
            btnAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_cmbUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox chckAdmin;
    private javax.swing.JCheckBox chckEstandar;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
