/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import java.util.ArrayList;
import java.util.Vector;
import modelo.Email;
import modelo.MiModeloTabla;
import modelo.Usuario;

/**
 *
 * @author Yesica
 */
public class PnlLeer extends javax.swing.JPanel {

    Empresa empresa;
    MiModeloTabla modeloTabla;
    Usuario usuario;

    /**
     *
     * @param empresa
     * @param usuario
     */
    public PnlLeer(Empresa empresa, Usuario usuario) {
        initComponents();
        this.empresa = empresa;
        this.usuario = usuario;
        modeloTabla = new MiModeloTabla();
        String[] titulos = {"De", "Asunto"};//titulos de las columnas de la tabla
        modeloTabla.setColumnIdentifiers(titulos);//inserta los titulos escritos
        tblEmails.setModel(modeloTabla);
        cargarEmails(usuario.getEmails());
    }

    /**
     * Carga los emails en la tabla. Muestra el remitente y el asunto del
     * mensaje
     *
     * @param emails
     */
    private void cargarEmails(ArrayList<Email> emails) {
        for (Email e : emails) {
            /* for(tipo elemento:conjunto) este for se llama for each*/
            Vector v = new Vector();

            v.add(e);//va a poner en la primera columna un objeto mostrando sólo el remitente
            v.add(e.getAsunto());// va en la segunda columna
            modeloTabla.addRow(v);//añadir una fila
        }
    }

    /**
     * Restaura la pantalla a su estado por defecto
     */
    private void limpiar() {
        lblDe.setText("");
        lblAsunto.setText("");
        lblFecha.setText("");
        txtMensaje.setText("");
        chckLeido.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        tblEmails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        chckLeido = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmails.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tblEmails.setForeground(new java.awt.Color(0, 153, 153));
        tblEmails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmailsMouseClicked(evt);
            }
        });
        panelScroll.setViewportView(tblEmails);

        add(panelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 180));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Leer mensajes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        lblDe.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblDe.setForeground(new java.awt.Color(0, 204, 204));
        add(lblDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 150, 30));

        lblFecha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 204, 204));
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 150, 30));

        lblAsunto.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblAsunto.setForeground(new java.awt.Color(0, 204, 204));
        add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 150, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Asunto:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("De:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        Aceptar.setBackground(new java.awt.Color(255, 255, 204));
        Aceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        chckLeido.setBackground(new java.awt.Color(255, 204, 204));
        chckLeido.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chckLeido.setForeground(new java.awt.Color(0, 204, 204));
        chckLeido.setText("Leído");
        add(chckLeido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        txtMensaje.setEditable(false);
        txtMensaje.setBackground(new java.awt.Color(255, 255, 204));
        txtMensaje.setColumns(20);
        txtMensaje.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtMensaje.setRows(5);
        jScrollPane1.setViewportView(txtMensaje);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 470, 150));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmailsMouseClicked
        Email seleccionado;//creo un objeto tipo email
        int fila = tblEmails.rowAtPoint(evt.getPoint());
        // int columna = tabla.columnAtPoint(e.getPoint()); no me interesa la columna ha pulsado
        if ((fila > -1) /*&& (columna > -1)*/) {
            seleccionado = (Email) modeloTabla.getValueAt(fila, 0);
            lblDe.setText(seleccionado.getDe());
            lblAsunto.setText(seleccionado.getAsunto());
            lblFecha.setText(seleccionado.getFecha());
            txtMensaje.setText(seleccionado.getMensaje());
            chckLeido.setSelected(true);
            seleccionado.setLeido(true);

        }

    }//GEN-LAST:event_tblEmailsMouseClicked

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        limpiar();
    }//GEN-LAST:event_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JCheckBox chckLeido;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JTable tblEmails;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables
}
